### ISSUE TITLE
Pb with MQTT connection from landroid-cloud2domoticz.js

### ISSUE THREAD

**Issue by JRB202** [mjiderhamn/worx-landroid-nodejs#17] opened 2017-09-14 21:19 UTC
I am running following config :
Ubuntu 16.04
nodejs v4.2.6
domoticz V3.8153
mosquito V1.4.9 for MQTT support 

**Connection with domoticz is OK
but connection with MQTT client fails :**
--------------------------------------------------------------------------------------------------------
administrator@ubuntu:~/worx-landroid-nodejs$ nodejs landroid-cloud2domoticz.js
UUID: 5356ad30-998c-11e7-xxxxxxxxxxxxxxxxxx
Initializing devices on http://localhost:8080
MQTT hardware found in Domoticz
Devices identified: {"Worx Landroid Battery":1,"Worx Landroid Mowing Hours":2,"Worx Landroid No Of Alarms":3,"Worx Landroid Alert":4,"Worx Landroid Message":5}
Making sure device exists: Worx Landroid Battery
Making sure device exists: Worx Landroid Mowing Hours
Making sure device exists: Worx Landroid No Of Alarms
Making sure device exists: Worx Landroid Alert
Making sure device exists: Worx Landroid Message
Done initializing Domoticz devices
You can now navigate to http://localhost:8080/#/Utility to see your Landroid status
Connecting to MQTT broker at mqtt://localhost...
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/lib/client.js:671:9)
    at MqttClient._handlePacket (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/lib/client.js:271:12)
    at process (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/lib/client.js:218:12)
    at Writable.writable._write (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/lib/client.js:228:5)
    at doWrite (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/home/administrator/worx-landroid-nodejs/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

-----------------------------------------------------------------------------------------------------

Message from mosquitto:

administrator@ubuntu:~$ sudo systemctl status mosquitto.service
[sudo] Mot de passe de administrator :
● mosquitto.service - Insite_MQTT_Broker
   Loaded: loaded (/etc/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: active (running) since jeu. 2017-09-14 22:25:54 CEST; 47min ago
 Main PID: 25977 (mosquitto)
    Tasks: 1
   Memory: 580.0K
      CPU: 1.903s
   CGroup: /system.slice/mosquitto.service
           └─25977 /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

sept. 14 23:12:25 ubuntu mosquitto[25977]: 1505423545: Socket error on client <unknown>, disconnecting.
sept. 14 23:12:25 ubuntu mosquitto[25977]: Socket error on client <unknown>, disconnecting.
sept. 14 23:12:55 ubuntu mosquitto[25977]: 1505423575: New connection from ::1 on port 1883.
sept. 14 23:12:55 ubuntu mosquitto[25977]: New connection from ::1 on port 1883.
sept. 14 23:12:55 ubuntu mosquitto[25977]: 1505423575: Socket error on client <unknown>, disconnecting.
sept. 14 23:12:55 ubuntu mosquitto[25977]: Socket error on client <unknown>, disconnecting.
sept. 14 23:13:26 ubuntu mosquitto[25977]: 1505423605: New connection from ::1 on port 1883.
sept. 14 23:13:26 ubuntu mosquitto[25977]: New connection from ::1 on port 1883.
sept. 14 23:13:26 ubuntu mosquitto[25977]: 1505423605: Socket error on client <unknown>, disconnecting.
sept. 14 23:13:26 ubuntu mosquitto[25977]: Socket error on client <unknown>, disconnecting.

What could be the problem ?

**Comment by JRB202** [comment] 2017-09-14 22:48
I reinstalled mosquitto from 
http://mosquitto.org/2013/01/mosquitto-debian-repository/

Mosquitto is running fine but 
I have a new error:

administrator@ubuntu:~/worx-landroid-nodejs$ nodejs landroid-cloud2domoticz.js
UUID: 118ec060-999e-11e7-b9ca-6b91c811e65a
Initializing devices on http://localhost:8080
MQTT hardware found in Domoticz
Devices identified: {"Worx Landroid Battery":1,"Worx Landroid Mowing Hours":2,"Worx Landroid No Of Alarms":3,"Worx Landroid Alert":4,"Worx Landroid Message":5,"VirtualTempSensor-1":6}
Making sure device exists: Worx Landroid Battery
Making sure device exists: Worx Landroid Mowing Hours
Making sure device exists: Worx Landroid No Of Alarms
Making sure device exists: Worx Landroid Alert
Making sure device exists: Worx Landroid Message
Done initializing Domoticz devices
You can now navigate to http://localhost:8080/#/Utility to see your Landroid status
Connecting to MQTT broker at mqtt://localhost...
Connected to MQTT broker
Connected to Domoticz MQTT, connect to Landroid MQTT
Downloaded guest token
API token set to qiJNz3waS4I99FPvTaxxxxxxxxxxxxxxxxxxxxxxx
Logged in as jrboulet@gmail.com - user token retrieved from API
API token set to RTrxTOyaqUo0N3xxxxxxxxxxxxxxxxxxxxxxxxx
Certificate retrieved
/home/administrator/worx-landroid-nodejs/landroid-cloud.js:118
        decoded = Buffer.from(data.pkcs12, 'base64');
                         ^
TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at /home/administrator/worx-landroid-nodejs/landroid-cloud.js:118:26
    at Object.najax.success (/home/administrator/worx-landroid-nodejs/landroid-cloud.js:256:9)
    at fire (/home/administrator/worx-landroid-nodejs/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.self.fireWith (/home/administrator/worx-landroid-nodejs/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.self.fire [as resolve] (/home/administrator/worx-landroid-nodejs/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)

**Comment by JRB202** [comment] 2017-09-14 23:48
I think I fixed the problem by upgrading nodejs to V6

===> But I do not see any value updated in domoticz devices

Here is the result 

administrator@ubuntu:~/worx-landroid-nodejs$ nodejs landroid-cloud2domoticz.js
UUID: 9dda74d0-99a6xxxxxxxxxxxxxxxxxxxxxxxxxx
Initializing devices on http://localhost:8080
MQTT hardware found in Domoticz
Devices identified: {"VirtualTempSensor-1":6,"Worx Landroid Battery":7,"Worx Landroid Mowing Hours":8,"Worx Landroid No Of Alarms":9,"Worx Landroid Alert":10,"Worx Landroid Message":11}
Making sure device exists: Worx Landroid Battery
Making sure device exists: Worx Landroid Mowing Hours
Making sure device exists: Worx Landroid No Of Alarms
Making sure device exists: Worx Landroid Alert
Making sure device exists: Worx Landroid Message
Done initializing Domoticz devices
You can now navigate to http://localhost:8080/#/Utility to see your Landroid status
Connecting to MQTT broker at mqtt://localhost...
Connected to MQTT broker
Connected to Domoticz MQTT, connect to Landroid MQTT
Downloaded guest token
API token set to qiJNz3waS4I99FPxxxxxxxxxxxxxxxxxxxxxxxxx
Logged in as jrboulet@gmail.com - user token retrieved from API
API token set to RTrxTOyaqUo0Nxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Certificate retrieved
Fetching root CA
Connecting to MQTT broker
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut
Connected to MQTT broker - subscribing to DB510/A62BB0206BAA/commandOut

**Comment by JRB202** [comment] 2017-09-18 11:11
I had more investigations:
I uncommented that line in landroid-cloud.js
console.log('MQTT message received: ' + JSON.stringify(data));

This line is never displayed.

So apparently connection to landroid MQTT broker is OK 
but subscribtion is not done and then no message can be received

Any idea ?

**Comment by JRB202** [comment] 2017-10-06 22:00
I have this new error since I upgraded my landroid WR105SI to firmware V2.85 :

Connecting to MQTT broker at mqtt://localhost...
Connected to MQTT broker
Connected to Domoticz MQTT, connect to Landroid MQTT
Downloaded guest token
API token set to qiJNxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Logged in as xxxxxxxxxxx@gmail.com - user token retrieved from API
API token set to RTrxTOyaqUxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Certificate retrieved
Fetching root CA
Connecting to Landroid MQTT broker
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**Comment by Bouni** [comment] 2017-10-08 18:31
Check out issue #19

**Comment by mjiderhamn** [comment] 2017-10-09 11:02
Closing this as a duplicate of #19

**Closed by mjiderhamn** 2017-10-09 11:02 UTC
